#!/usr/bin/env bash
set -e

cd pil21
rm -rf -- *
wget -q https://software-lab.de/pil21.tgz
if [ -s "pil21.tgz" ]; then
	tar -zxf pil21.tgz --strip-components=1
	rm pil21.tgz

	git add .
	git commit -aqm "." > /dev/null
	git push -q
fi
